#!/usr/bin/env python3
"""Write web/assets/address_blocks.js: the ICAO address blocks, so a page
names an aircraft's state of registration from its hex the moment it has
one, without asking /v1/airframes/{hex}.

Source: api/app/address_blocks.py, whose BLOCKS the Rust copy
(networkd's address_blocks.rs) is generated from too; keep all three
equal. --check exits 1 when the asset is out of date.

    python3 tools/address_blocks_asset.py [--check]
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DST = os.path.join(ROOT, "web", "assets", "address_blocks.js")
sys.path.insert(0, os.path.join(ROOT, "api"))

from app.address_blocks import BLOCKS  # noqa: E402


def render():
    rows = ",\n".join(f'  [0x{a:06X}, 0x{b:06X}, "{s}"]' for a, b, s in BLOCKS)
    return (
        "/* ICAO 24-bit address blocks -> ISO state, sorted by first address.\n"
        "   Generated by tools/address_blocks_asset.py from\n"
        "   api/app/address_blocks.py; do not edit. fpHistory.stateOf(hex)\n"
        "   reads it. */\n"
        f"window.fpAddressBlocks = [\n{rows}\n];\n"
    )


def main():
    text = render()
    if "--check" in sys.argv:
        try:
            current = open(DST, encoding="utf-8").read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print(f"{DST} is out of date: python3 tools/address_blocks_asset.py")
            sys.exit(1)
        return
    with open(DST, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"{DST}: {len(BLOCKS)} blocks")


if __name__ == "__main__":
    main()
